apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-servicemonitor
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: myapp
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
