apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet
  labels:
    team: infra
spec:
  selector:
    matchLabels:
      k8s-app: kubelet
  endpoints:
    - port: https-metrics
      interval: 15s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    any: true
