prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        team: backend

    podMonitorSelector:
      matchLabels:
        team: backend

    ruleSelector:
      matchLabels:
        role: alert-rules

    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

alertmanager:
  alertmanagerSpec:
    replicas: 2
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  adminUser: admin
  adminPassword: "YourStrongPasswordHere"
  service:
    type: LoadBalancer
  ingress:
    enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
