prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        team: backend

    podMonitorSelector:
      matchLabels:
        team: backend

    ruleSelector:
      matchLabels:
        role: alert-rules

    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard # Or your preferred storage class
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 100Gi
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1
        memory: 4Gi

    alertmanager:
      alertmanagerSpec:
        replicas: 2
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: standard # Or your preferred storage class
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 20Gi
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 400Mi

    grafana:
      adminUser: admin
      adminPassword: "YourNewStrongPassword" # Change this!
      service:
        type: LoadBalancer
      ingress:
        enabled: false

    nodeExporter:
      enabled: true

    kubeStateMetrics:
      enabled: true
