apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: app-podmonitor
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: myapp
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
