name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go (for promtool)
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Install promtool
        run: |
          curl -LO https://github.com/prometheus/prometheus/releases/download/v2.44.0/prometheus-2.44.0.linux-amd64.tar.gz
          tar xzf prometheus-2.44.0.linux-amd64.tar.gz
          sudo mv prometheus-2.44.0.linux-amd64/promtool /usr/local/bin/
          rm -rf prometheus-2.44.0.linux-amd64*

      - name: Validate Prometheus rules
        run: ./scripts/validate-rules.sh

      - name: Helm lint
        run: helm lint helm/

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate
